### ISSUE TITLE
Making Navbar mobile responsive

### ISSUE THREAD

**Issue by kamalbuilds** [legendarykamal/Lets-go-shop#28] opened 2022-08-21 10:06 UTC
#### Description

Currently Cart button doesn't behaves desired way
#### Environment:
- Host OS: 
- Browser:

**Comment by CalebCyrill** [comment] 2022-08-21 23:30
What is the desired outcome that you are looking for? Do you want the cart button to move or be hidden from view?

**Comment by kamalbuilds** [comment] 2022-08-22 16:06
@CalebCyrill  Desired
![image](https://user-images.githubusercontent.com/95926324/185966664-7c0de274-fdce-4e43-b636-704d41742fea.png)

Now- at 371 px it breaks off we want the dewsign to be consistent for upto atleast 300px;
![image](https://user-images.githubusercontent.com/95926324/185967106-70186f28-1dd7-45c9-b618-725bea8e343c.png)

**Comment by kamalbuilds** [comment] 2022-08-22 16:06
also @CalebCyrill could you try using this app and you can probably file some issues , that would be great .

**Comment by kamalbuilds** [comment] 2022-08-25 02:07
@CalebCyrill do you wish to get assigned?

**Comment by CalebCyrill** [comment] 2022-08-25 03:19
You can assign it to me

**Comment by kamalbuilds** [comment] 2022-08-25 03:34
Perfect 💯

**Comment by CalebCyrill** [comment] 2022-08-29 05:59
@legendarykamal what are you using to change the dimensions of the page? Seems like you can do it rather quickly. I am currently using the dev tools and resizing manually

**Comment by kamalbuilds** [comment] 2022-09-03 07:25
yeah same I too use dev tools :smile: 

what are the updates on this issue?

**Comment by CalebCyrill** [comment] 2022-09-03 07:27
The issue is because of the padding on the nav. I am currently away from my
computer for the week and will be able to address the issue on Thursday

**Comment by kamalbuilds** [comment] 2022-09-06 15:13
ok @CalebCyrill :+1:

**Closed as completed** 2022-09-23 02:16 UTC
Labels: good first issue
